/*import { Aliment } from './aliment';

const ALIMENT_DATA: Aliment [] =
     [
        {
            id: 1,
            name: 'Ananas',
            category: 'fruits frais',
            energy: 53.2,
            ig: 63,
            protein: 0.52,
            carb: 11,
            sugar: 10.4,
            lipid: 0.24,
            fibre: 1.33,
            salt: 0.0024,
            cg: 30
        },
        {
            id: 2,
            name: 'Artichaud',
            category: 'légumes cuits',
            energy: 33.2,
            ig: 20,
            protein: 2.53,
            carb: 0.99,
            sugar: 0.99,
            lipid: 0.28,
            fibre: 8.3,
            salt: 0.14,
            cg: 60
        },
        {
            id: 3,
            name: 'Banane',
            category: 'fruits frais',
            energy: 90,
            ig: 65,
            protein: 0.98,
            carb: 19.6,
            sugar: 14.8,
            lipid: 0.25,
            fibre: 1.9,
            salt: 0.0038,
            cg: null,
        },
        {
            id: 4,
            name: 'Abricot',
            category: 'fruits frais',
            energy: 42.6,
            ig: 30,
            protein: 1.86,
            carb: 39.8,
            sugar: 36.6,
            lipid: 0.51,
            fibre: 5.7,
            salt: 0.098,
            cg: 40
        },
        {
            id: 5,
            name: 'Bar commun ou loup',
            category: 'poissons cuits',
            energy: 147,
            ig: 14,
            protein: 22.2,
            carb: 41.2,
            sugar: 0,
            lipid: 6.51,
            fibre: 0,
            salt: 0.0038,
            cg: null,
        },
        {
            id: 6,
            name: 'Fenouil',
            category: 'légumes frais',
            energy: 58,
            ig: 2,
            protein: 1.9,
            carb: 0.89,
            sugar: 0.4,
            lipid: 4.61,
            fibre: 3,
            salt: 0,
            cg: null,
        },
    ]
;
export default ALIMENT_DATA;*/
